[package]
name = "ir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
iced-x86 = { version = "1.18.0", default-features = false, features = ["std", "decoder", "instr_info"] }
